#!/usr/bin/env bash
set -e

# @section_code: SC000
# @section_name: blueprint
# @blueprint_name: SSP
# @blueprint_version: 1.0
# @blueprint_url: https://mush.javanile.org/blueprint/

# @section_code: SC001
# @section_name: file-meta
# @package: code_dumper
# @file_type: build-library
# @build_type: lib
# @build_date: 2026-03-22T17:45:51Z

# @section_code: SC005
# @section_name: functions
use() { return 0; }
extern() { return 0; }
legacy() { return 0; }
module() { return 0; }
public() { return 0; }
embed() { return 0; }
inject() { return 0; }

# @section_code: SC007
# @section_name: source
# @source_index: 1
# @source_file: /home/francesco/.mush/registry/src/github-javanile-mush/name_convention/0.2.0/packages/name_convention/src/lib.sh
# @portion_type: lib


code_dumper_error() {
  cavallo
  echo -e "\e[K\e[0m\e[1m\e[38;5;9merror\e[0m\e[0m\e[1m: expected item, found keyword \`if\`\e[0m"
  echo -e "\e[0m  \e[0m\e[0m\e[1m\e[38;5;12m--> \e[0m\e[0msrc/main.rs:39:1\e[0m"
  echo -e "\e[0m   \e[0m\e[0m\e[1m\e[38;5;12m|\e[0m"
  echo -e "\e[0m\e[1m\e[38;5;12m39\e[0m\e[0m \e[0m\e[0m\e[1m\e[38;5;12m|\e[0m\e[0m \e[0m\e[0mif 6 < 7 {\e[0m"
  echo -e "\e[0m   \e[0m\e[0m\e[1m\e[38;5;12m| \e[0m\e[0m\e[1m\e[38;5;9m^^\e[0m\e[0m \e[0m\e[0m\e[1m\e[38;5;9mexpected item\e[0m"
}
